### PR TITLE
add notebook showing model score discretisation

### PR DESCRIPTION
**Pull request by joaopcnogueira**
Add an example to illustrate how we can use the discretisation methods to binnarize the model probability output.

### CODE REVIEW

**Comment by solegalli** [comment]
Hi @joaopcnogueira 

This notebooks is really interesting, thank you!

You could make a blog out of it and publish it on medium. I would encourage you to do that actually. It is not something that I see discussed a lot, so it would be something different to read about, for once :)

I am merging now, and apologies for the delay. I was on holidays till yesterday.

**Comment by joaopcnogueira** [comment]
Thank you very much for accept it! I will blog it on both medium and my personal blog page. I'll let you know here and again, really appreciate all of the work you've been doing with feature-engine!

**Comment by joaopcnogueira** [comment]
Hello there @solegalli! Just coming back to share the notebook on my blog, as you suggested. Thank you very much!

https://joaopcnogueira.github.io/machine-learning-blog/01_model_probability_discretisation.html

**Comment by solegalli** [comment]
I'll share it on social media later in the month :)

**Pull request merged**
